# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171110_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postimage',
            new_name='image',
        ),
    ]
